"""Initial migration

Revision ID: 5dad2eec8d1d
Revises: 
Create Date: 2020-02-19 02:00:31.023303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dad2eec8d1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('audio_file', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'audio_file')
    # ### end Alembic commands ###
